version: '3.8'
services:
  php-app:
    build:
      context: .
    ports:
      - "8087:80" 
    volumes:
      - fde-data:/var/www/data/
    environment:
      USER_AUTH_PASSWORD: abc
      CLIENT_AUTH_KEY: xyz
      AES_KEY: xxx
      LOG_FILE_PATH: log.txt
    restart: always
volumes:
  fde-data: