version: '3.8'
services:
  php-app:
    image: php:8.2-apache #change to actual image
    ports:
      - "8087:80" 
    volumes:
      - fde-data:/var/www/data/
    environment:
      USER_AUTH_PASSWORD: abc
      CLIENT_AUTH_KEY: xyz
      AES_KEY: xxx
      AES_IV: d7575a8ffbce7bbc
      LOG_FILE_PATH: /var/www/data/log.txt
    restart: always
volumes:
  fde-data: